/**
 * GDGC AIKTC - Official Events & Community Programs Data
 * Google Developer Groups on Campus · Anjuman-I-Islam Kalsekar Technical Campus
 */

export const officialChapterUrl =
  'https://gdg.community.dev/gdg-on-campus-anjuman-i-islams-kalsekar-technical-campus-navi-mumbai-india/#eeSGPsrOVmy';

export const eventCategories = [
  { id: 'all', name: 'All Events', icon: 'Sparkles' },
  { id: 'upcoming', name: 'Upcoming', icon: 'Calendar' },
  { id: 'workshops', name: 'Workshops', icon: 'Layers' },
  { id: 'study-jams', name: 'Study Jams', icon: 'BookOpen' },
  { id: 'hackathons', name: 'Hackathons', icon: 'Code2' },
  { id: 'past', name: 'Past Archive', icon: 'History' },
];

export const upcomingEvents = [
  {
    id: 'fe-2026-solution-challenge',
    title: 'Google Solution Challenge & GenAI Study Jam',
    isFeatured: true,
    category: 'study-jams',
    categoryName: 'Study Jam & Sprint',
    accentColor: 'blue',
    status: 'upcoming',
    statusLabel: 'RSVP via Chapter',
    schedule: 'Spring Season · Date TBA',
    time: 'Hybrid · Campus & Virtual',
    location: 'AIKTC Seminar Hall / Google Meet',
    description:
      'Kickoff for building real-world solutions addressing UN Sustainable Development Goals using Google Gemini API, Vertex AI, and Google Cloud technologies.',
    tags: ['Gemini API', 'Google Cloud', 'Solution Challenge', 'GenAI'],
    audience: 'Open to All Students',
    image: '/images/events/solution-challenge-kickoff.png',
    imageAlt: 'Google Solution Challenge and Build with AI kickoff presentation',
    imageDisclaimer: '',
    registrationUrl: officialChapterUrl,
    registrationNote: 'RSVP directly on the official GDGC Chapter portal.',
  },
  {
    id: 'ev-web-modern-fullstack',
    title: 'Modern Web Jam: React 19, Vite & Tailwind CSS',
    isFeatured: false,
    category: 'workshops',
    categoryName: 'Hands-on Workshop',
    accentColor: 'blue',
    status: 'upcoming',
    statusLabel: 'Announcing Soon',
    schedule: 'Spring Season · Date TBA',
    time: '2-Hour Hands-on Session',
    location: 'Computer Lab 3, AIKTC Campus',
    description:
      'Learn how modern frontend engineering works in 2026. Build performant single-page apps with React 19 hooks, Vite bundler, and atomic Tailwind styling.',
    tags: ['React 19', 'Vite', 'Tailwind CSS', 'Frontend'],
    audience: 'Open to All Branches & Skill Levels',
    image: '/images/events/web-dev-bootcamp.jpg',
    imageAlt: 'Students and speaker at AIKTC during Web Development Boot Camp Kickoff',
    imageDisclaimer: '',
    registrationUrl: officialChapterUrl,
    registrationNote: 'Dates and seat booking releasing soon on Chapter portal.',
  },
  {
    id: 'ev-cloud-practitioner-sprint',
    title: 'Google Cloud Study Jam: Cloud Run & Serverless 101',
    isFeatured: false,
    category: 'study-jams',
    categoryName: 'Cloud Study Jam',
    accentColor: 'green',
    status: 'upcoming',
    statusLabel: 'Announcing Soon',
    schedule: 'Upcoming Weekend Track',
    time: 'Virtual Hands-on Sprint',
    location: 'Google Meet / Online',
    description:
      'Deploy your first containerized microservice without managing servers. Explore Cloud Run, Artifact Registry, and Google Cloud Skill Boost pathways.',
    tags: ['Google Cloud', 'Cloud Run', 'Docker', 'DevOps'],
    audience: 'Beginners to Intermediate',
    image: '/images/events/gke-kubernetes-cloud.jpg',
    imageAlt: 'Microservices architecture and cloud deployment session on GKE',
    imageDisclaimer: '',
    registrationUrl: officialChapterUrl,
    registrationNote: 'RSVP will open via official GDGC chapter mailers.',
  },
  {
    id: 'ev-android-compose-camp',
    title: 'Android Compose Camp: Declarative UIs in Kotlin',
    isFeatured: false,
    category: 'workshops',
    categoryName: 'Mobile Dev Workshop',
    accentColor: 'yellow',
    status: 'upcoming',
    statusLabel: 'Upcoming',
    schedule: 'Mid-Semester Workshop',
    time: 'Half-Day Boot Camp',
    location: 'AIKTC Tech Center',
    description:
      'Step away from legacy XML layouts. Experience modern Android development with Jetpack Compose, Material 3, and state management in Kotlin.',
    tags: ['Android', 'Kotlin', 'Jetpack Compose', 'Mobile'],
    audience: 'Curious developers & Android enthusiasts',
    image: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Android developer testing application layout on device',
    imageDisclaimer: 'Representative event visual preview',
    registrationUrl: officialChapterUrl,
    registrationNote: 'Prerequisites & setup guide published on Chapter page.',
  },
  {
    id: 'ev-ai-hackathon-prep',
    title: 'Solution Sprint: Ideation to MVP Hackathon Prep',
    isFeatured: false,
    category: 'hackathons',
    categoryName: 'Hackathon Sprint',
    accentColor: 'red',
    status: 'upcoming',
    statusLabel: 'Planning Phase',
    schedule: 'Pre-Hackathon Briefing',
    time: 'Interactive Workshop',
    location: 'AIKTC Seminar Hall',
    description:
      'How do winning hackathon teams brainstorm, scope their minimum viable product, and deliver compelling 3-minute demos to judges? A collaborative ideation lab.',
    tags: ['Ideation', 'Prototyping', 'Pitching', 'Solution Challenge'],
    audience: 'Hackathon participants & builders',
    image: '/images/events/pitch-carnival.jpg',
    imageAlt: 'Startup pitch presentation in AIKTC auditorium during Pitch Carnival',
    imageDisclaimer: '',
    registrationUrl: officialChapterUrl,
    registrationNote: 'Team formation details announced via chapter community.',
  },
];

export const pastEvents = [
  {
    id: 'past-techsprint-hackathon-2026',
    title: 'TechSprint Hackathon',
    term: '5 Dec 2025 – 10 Jan 2026 · Online',
    category: 'past',
    topicCategory: 'hackathons',
    categoryType: 'Hackathon',
    accentColor: 'red',
    description:
      'A multi-week virtual hackathon where students collaborated to build and pitch innovative software solutions. Drew 600 registrations, 70 project submissions, and 10 finalist teams.',
    takeaways: [
      '600 registrations & 70 project submissions across student builder teams',
      '10 finalist teams selected for final rounds',
      'Winners: Team SPOT, ChaiGPT, and Neural Nexus',
    ],
    tags: ['Hackathon', 'TechSprint', 'Prototyping', 'Student Builders', 'Online'],
    image: '/images/events/techsprint-hackathon.png',
    imageAlt: 'Team Chai GPT presenting live during TechSprint Hackathon Finale on Google Meet',
    imageDisclaimer: '',
    chapterRecapUrl: officialChapterUrl,
  },
  {
    id: 'past-google-gemini-workshop-2025',
    title: 'Google Gemini Workshop',
    term: '16 Dec 2025 · 4:00 PM–6:00 PM · Online',
    category: 'past',
    topicCategory: 'workshops',
    categoryType: 'Hands-on Workshop',
    accentColor: 'blue',
    description:
      'Interactive online workshop exploring Google Gemini and Generative AI applications. Covered prompt engineering workflows, AI productivity tools, and responsible AI practices.',
    takeaways: [
      'Conducted by Iffah Sarang with 50 registered student participants',
      'Explored Google Gemini, prompt engineering & GenAI applications',
      'Practical insights into productivity tools and responsible AI',
    ],
    tags: ['Google Gemini', 'Generative AI', 'Prompt Engineering', 'Productivity', 'Responsible AI', 'Iffah Sarang'],
    image: '/images/events/gemini-workshop.jpg',
    imageAlt: 'Iffah Sarang presenting Google Gemini prompt engineering and generative AI workflows',
    imageDisclaimer: '',
    chapterRecapUrl: officialChapterUrl,
  },
  {
    id: 'past-github-workshop-2025',
    title: 'GitHub Workshop',
    term: '18 Dec 2025 · 4:00 PM–6:00 PM · Online',
    category: 'past',
    topicCategory: 'workshops',
    categoryType: 'Hands-on Workshop',
    accentColor: 'green',
    description:
      'Practical virtual session on Git and GitHub fundamentals for modern developers. Covered repositories, branching, pull requests, and collaborative developer workflows.',
    takeaways: [
      'Conducted by Abdul Rehman Kalsekar with 50 registered attendees',
      'Mastered Git & GitHub fundamentals, repository setup, and commits',
      'Hands-on practice with branching, pull requests, and collaboration',
    ],
    tags: ['Git', 'GitHub', 'Repositories', 'Branching', 'Pull Requests', 'Collaboration', 'Abdul Rehman Kalsekar'],
    image: '/images/events/github-workshop.jpg',
    imageAlt: 'Abdul Rehman Kalsekar conducting GitHub Mastery workshop on repositories and version control',
    imageDisclaimer: '',
    chapterRecapUrl: officialChapterUrl,
  },
  {
    id: 'past-genai-study-jams-2025',
    title: 'Gen AI Study Jams 2025',
    term: '1–31 Oct 2025 · Online',
    category: 'past',
    topicCategory: 'study-jams',
    categoryType: 'Study Jam',
    accentColor: 'yellow',
    description:
      'A month-long virtual learning program focused on Generative AI and machine learning via Google Cloud Skills Boost. Achieved prestigious Tier One recognition with strong cohort engagement.',
    takeaways: [
      '250 registrations with 108 successful student completions',
      'Achieved prestigious Tier One recognition for chapter milestone completion',
      'Hands-on learning labs across Generative AI, Machine Learning, and Cloud Skills Boost',
    ],
    tags: ['Generative AI', 'Study Jam', 'Machine Learning', 'Cloud Skills Boost', 'Tier One', 'Google Cloud'],
    image: '/images/events/genai-study-jam.jpg',
    imageAlt: 'GDGC AIKTC chapter team and participants celebrating Gen AI Study Jams completion with swag',
    imageDisclaimer: '',
    chapterRecapUrl: officialChapterUrl,
  },
  {
    id: 'past-info-session-2025',
    title: 'GDGC AIKTC Chapter Kickoff & Orientation',
    term: 'Chapter Inaugural Session',
    category: 'past',
    topicCategory: 'community',
    categoryType: 'Community Orientation',
    accentColor: 'blue',
    description:
      'Introduction to Google Developer Groups on Campus at AIKTC. Overview of upcoming technical tracks, open source initiatives, and developer opportunities for students.',
    takeaways: [
      'Introduced Chapter core team and domain leads',
      'Walked through Google Cloud, Android, and Web roadmaps',
      'Community Q&A and networking session',
    ],
    tags: ['Orientation', 'Community', 'Google For Developers'],
    image: '/images/events/chapter-kickoff.jpg',
    imageAlt: 'GDGC AIKTC chapter kickoff, community member felicitation, and faculty in seminar hall',
    imageDisclaimer: '',
    chapterRecapUrl: officialChapterUrl,
  },
  {
    id: 'past-git-github-workshop',
    title: 'Git & GitHub Hands-on: Zero to First Open-Source PR',
    term: 'Fall Technical Bootcamp',
    category: 'past',
    topicCategory: 'workshops',
    categoryType: 'Hands-on Bootcamp',
    accentColor: 'green',
    description:
      'Students learned local version control, branch workflows, merge conflict resolution, and published their first open-source contributions.',
    takeaways: [
      'Configured Git CLI and SSH keys',
      'Mastered feature-branch workflows and rebasing basics',
      'Simulated team pull requests and peer code review',
    ],
    tags: ['Git', 'GitHub', 'Open Source', 'Collaboration'],
    image: '/images/events/backend-bootcamp.jpg',
    imageAlt: 'Hands-on developer bootcamp at AIKTC seminar hall with students coding on laptops',
    imageDisclaimer: '',
    chapterRecapUrl: officialChapterUrl,
  },
  {
    id: 'past-cloud-study-jam-genai',
    title: 'Google Cloud GenAI Foundations Study Jam',
    term: 'Hands-on Sprint Session',
    category: 'past',
    topicCategory: 'study-jams',
    categoryType: 'Study Jam',
    accentColor: 'yellow',
    description:
      'Guided cohort through Google Cloud Skills Boost labs, earning skill badges in Prompt Design in Vertex AI and Gemini APIs.',
    takeaways: [
      'Explored Google Cloud Console and Vertex AI Studio',
      'Completed interactive labs and earned skill badges',
      'Built prompt prototypes with zero-shot and few-shot techniques',
    ],
    tags: ['Google Cloud', 'Generative AI', 'Vertex AI', 'Skill Badges'],
    image: '/images/events/genai-foundations-lab.jpg',
    imageAlt: 'Interactive Google Cloud Arcade and GenAI chatbot lab session during Study Jam',
    imageDisclaimer: '',
    chapterRecapUrl: officialChapterUrl,
  },
  {
    id: 'past-solution-showcase',
    title: 'Student Project Showcase & Lightning Talks',
    term: 'Community Demo Day',
    category: 'past',
    topicCategory: 'showcase',
    categoryType: 'Showcase',
    accentColor: 'red',
    description:
      'Campus innovators presented semester projects built with Flutter, Firebase, and Web technologies to peers and mentors for live feedback.',
    takeaways: [
      'Live demos of student-built web and mobile applications',
      'Constructive technical critique and architecture tips',
      'Cross-departmental collaboration and peer connections',
    ],
    tags: ['Showcase', 'Lightning Talks', 'Student Builders'],
    image: '/images/events/student-showcase.jpg',
    imageAlt: 'Student presenter demonstrating live MVP prototype during Solution Challenge project submission',
    imageDisclaimer: '',
    chapterRecapUrl: officialChapterUrl,
  },
];
